version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    pin-versions: true
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
