version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - ".github/workflows/release.yml"
    groups:
      all-actions:
        patterns: [ "*" ]
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

